// Static/verbose data kept out of main.mjs: the ROM tree manifest and the
// SVG icon strings.

const ROMLIB = '../../romlib';
const TESTDATA = '../../tests/testdata';

const rom = (path) => ({ type: 'rom', path });
const dir = (children) => ({ type: 'dir', children });

// ROM_TREE generated by Claude based on current files used in test suite and rom library

export const ROM_TREE = dir({
    library: dir({
        alien3: rom(`${ROMLIB}/alien3.gb`),
        bart: rom(`${ROMLIB}/bart.gb`),
        drmario: rom(`${ROMLIB}/drmario.gb`),
        kirby: rom(`${ROMLIB}/kirby.gb`),
        metroid2: rom(`${ROMLIB}/metroid2.gb`),
        pinball: rom(`${ROMLIB}/pinball.gb`),
        pokeblue: rom(`${ROMLIB}/pokeblue.gb`),
        pokered: rom(`${ROMLIB}/pokered.gb`),
        pokeyellow: rom(`${ROMLIB}/pokeyellow.gb`),
        prehistorik: rom(`${ROMLIB}/prehistorik.gb`),
        supermarioland: rom(`${ROMLIB}/supermarioland.gb`),
        tetris: rom(`${ROMLIB}/tetris.gb`),
        zelda: rom(`${ROMLIB}/zelda.gb`),
    }),

    tests: dir({
        blargg: dir({
            cpu_instrs: dir({
                individual: dir({
                    '01-special': rom(`${TESTDATA}/blargg/cpu_instrs/individual/01-special.gb`),
                    '02-interrupts': rom(`${TESTDATA}/blargg/cpu_instrs/individual/02-interrupts.gb`),
                    '03-op sp,hl': rom(`${TESTDATA}/blargg/cpu_instrs/individual/03-op sp,hl.gb`),
                    '04-op r,imm': rom(`${TESTDATA}/blargg/cpu_instrs/individual/04-op r,imm.gb`),
                    '05-op rp': rom(`${TESTDATA}/blargg/cpu_instrs/individual/05-op rp.gb`),
                    '06-ld r,r': rom(`${TESTDATA}/blargg/cpu_instrs/individual/06-ld r,r.gb`),
                    '07-jr,jp,call,ret,rst': rom(`${TESTDATA}/blargg/cpu_instrs/individual/07-jr,jp,call,ret,rst.gb`),
                    '08-misc instrs': rom(`${TESTDATA}/blargg/cpu_instrs/individual/08-misc instrs.gb`),
                    '09-op r,r': rom(`${TESTDATA}/blargg/cpu_instrs/individual/09-op r,r.gb`),
                    '10-bit ops': rom(`${TESTDATA}/blargg/cpu_instrs/individual/10-bit ops.gb`),
                    '11-op a,(hl)': rom(`${TESTDATA}/blargg/cpu_instrs/individual/11-op a,(hl).gb`),
                }),
                cpu_instrs: rom(`${TESTDATA}/blargg/cpu_instrs/cpu_instrs.gb`),
            }),
            dmg_sound: dir({
                rom_singles: dir({
                    '01-registers': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/01-registers.gb`),
                    '02-len ctr': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/02-len ctr.gb`),
                    '03-trigger': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/03-trigger.gb`),
                    '04-sweep': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/04-sweep.gb`),
                    '05-sweep details': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/05-sweep details.gb`),
                    '06-overflow on trigger': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/06-overflow on trigger.gb`),
                    '07-len sweep period sync': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/07-len sweep period sync.gb`),
                    '08-len ctr during power': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/08-len ctr during power.gb`),
                    '09-wave read while on': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/09-wave read while on.gb`),
                    '10-wave trigger while on': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/10-wave trigger while on.gb`),
                    '11-regs after power': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/11-regs after power.gb`),
                    '12-wave write while on': rom(`${TESTDATA}/blargg/dmg_sound/rom_singles/12-wave write while on.gb`),
                }),
                dmg_sound: rom(`${TESTDATA}/blargg/dmg_sound/dmg_sound.gb`),
            }),
            mem_timing: dir({
                individual: dir({
                    '01-read_timing': rom(`${TESTDATA}/blargg/mem_timing/individual/01-read_timing.gb`),
                    '02-write_timing': rom(`${TESTDATA}/blargg/mem_timing/individual/02-write_timing.gb`),
                    '03-modify_timing': rom(`${TESTDATA}/blargg/mem_timing/individual/03-modify_timing.gb`),
                }),
                mem_timing: rom(`${TESTDATA}/blargg/mem_timing/mem_timing.gb`),
            }),
            'mem_timing-2': dir({
                rom_singles: dir({
                    '01-read_timing': rom(`${TESTDATA}/blargg/mem_timing-2/rom_singles/01-read_timing.gb`),
                    '02-write_timing': rom(`${TESTDATA}/blargg/mem_timing-2/rom_singles/02-write_timing.gb`),
                    '03-modify_timing': rom(`${TESTDATA}/blargg/mem_timing-2/rom_singles/03-modify_timing.gb`),
                }),
                mem_timing: rom(`${TESTDATA}/blargg/mem_timing-2/mem_timing.gb`),
            }),
            oam_bug: dir({
                rom_singles: dir({
                    '1-lcd_sync': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/1-lcd_sync.gb`),
                    '2-causes': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/2-causes.gb`),
                    '3-non_causes': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/3-non_causes.gb`),
                    '4-scanline_timing': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/4-scanline_timing.gb`),
                    '5-timing_bug': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/5-timing_bug.gb`),
                    '6-timing_no_bug': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/6-timing_no_bug.gb`),
                    '7-timing_effect': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/7-timing_effect.gb`),
                    '8-instr_effect': rom(`${TESTDATA}/blargg/oam_bug/rom_singles/8-instr_effect.gb`),
                }),
                oam_bug: rom(`${TESTDATA}/blargg/oam_bug/oam_bug.gb`),
            }),
            halt_bug: rom(`${TESTDATA}/blargg/halt_bug.gb`),
            instr_timing: rom(`${TESTDATA}/blargg/instr_timing/instr_timing.gb`),
        }),

        mealybug: dir({
            m2_win_en_toggle: rom(`${TESTDATA}/mealybug/m2_win_en_toggle.gb`),
            m3_bgp_change: rom(`${TESTDATA}/mealybug/m3_bgp_change.gb`),
            m3_bgp_change_sprites: rom(`${TESTDATA}/mealybug/m3_bgp_change_sprites.gb`),
            m3_lcdc_bg_en_change: rom(`${TESTDATA}/mealybug/m3_lcdc_bg_en_change.gb`),
            m3_lcdc_bg_en_change2: rom(`${TESTDATA}/mealybug/m3_lcdc_bg_en_change2.gb`),
            m3_lcdc_bg_map_change: rom(`${TESTDATA}/mealybug/m3_lcdc_bg_map_change.gb`),
            m3_lcdc_bg_map_change2: rom(`${TESTDATA}/mealybug/m3_lcdc_bg_map_change2.gb`),
            m3_lcdc_obj_en_change: rom(`${TESTDATA}/mealybug/m3_lcdc_obj_en_change.gb`),
            m3_lcdc_obj_en_change_variant: rom(`${TESTDATA}/mealybug/m3_lcdc_obj_en_change_variant.gb`),
            m3_lcdc_obj_size_change: rom(`${TESTDATA}/mealybug/m3_lcdc_obj_size_change.gb`),
            m3_lcdc_obj_size_change_scx: rom(`${TESTDATA}/mealybug/m3_lcdc_obj_size_change_scx.gb`),
            m3_lcdc_tile_sel_change: rom(`${TESTDATA}/mealybug/m3_lcdc_tile_sel_change.gb`),
            m3_lcdc_tile_sel_change2: rom(`${TESTDATA}/mealybug/m3_lcdc_tile_sel_change2.gb`),
            m3_lcdc_tile_sel_win_change: rom(`${TESTDATA}/mealybug/m3_lcdc_tile_sel_win_change.gb`),
            m3_lcdc_tile_sel_win_change2: rom(`${TESTDATA}/mealybug/m3_lcdc_tile_sel_win_change2.gb`),
            m3_lcdc_win_en_change_multiple: rom(`${TESTDATA}/mealybug/m3_lcdc_win_en_change_multiple.gb`),
            m3_lcdc_win_en_change_multiple_wx: rom(`${TESTDATA}/mealybug/m3_lcdc_win_en_change_multiple_wx.gb`),
            m3_lcdc_win_map_change: rom(`${TESTDATA}/mealybug/m3_lcdc_win_map_change.gb`),
            m3_lcdc_win_map_change2: rom(`${TESTDATA}/mealybug/m3_lcdc_win_map_change2.gb`),
            m3_obp0_change: rom(`${TESTDATA}/mealybug/m3_obp0_change.gb`),
            m3_scx_high_5_bits: rom(`${TESTDATA}/mealybug/m3_scx_high_5_bits.gb`),
            m3_scx_high_5_bits_change2: rom(`${TESTDATA}/mealybug/m3_scx_high_5_bits_change2.gb`),
            m3_scx_low_3_bits: rom(`${TESTDATA}/mealybug/m3_scx_low_3_bits.gb`),
            m3_scy_change: rom(`${TESTDATA}/mealybug/m3_scy_change.gb`),
            m3_scy_change2: rom(`${TESTDATA}/mealybug/m3_scy_change2.gb`),
            m3_window_timing: rom(`${TESTDATA}/mealybug/m3_window_timing.gb`),
            m3_window_timing_wx_0: rom(`${TESTDATA}/mealybug/m3_window_timing_wx_0.gb`),
            m3_wx_4_change: rom(`${TESTDATA}/mealybug/m3_wx_4_change.gb`),
            m3_wx_4_change_sprites: rom(`${TESTDATA}/mealybug/m3_wx_4_change_sprites.gb`),
            m3_wx_5_change: rom(`${TESTDATA}/mealybug/m3_wx_5_change.gb`),
            m3_wx_6_change: rom(`${TESTDATA}/mealybug/m3_wx_6_change.gb`),
        }),

        mooneye: dir({
            acceptance: dir({
                bits: dir({
                    mem_oam: rom(`${TESTDATA}/mooneye/acceptance/bits/mem_oam.gb`),
                    reg_f: rom(`${TESTDATA}/mooneye/acceptance/bits/reg_f.gb`),
                    'unused_hwio-GS': rom(`${TESTDATA}/mooneye/acceptance/bits/unused_hwio-GS.gb`),
                }),
                instr: dir({
                    daa: rom(`${TESTDATA}/mooneye/acceptance/instr/daa.gb`),
                }),
                interrupts: dir({
                    ie_push: rom(`${TESTDATA}/mooneye/acceptance/interrupts/ie_push.gb`),
                }),
                oam_dma: dir({
                    basic: rom(`${TESTDATA}/mooneye/acceptance/oam_dma/basic.gb`),
                    reg_read: rom(`${TESTDATA}/mooneye/acceptance/oam_dma/reg_read.gb`),
                    'sources-GS': rom(`${TESTDATA}/mooneye/acceptance/oam_dma/sources-GS.gb`),
                }),
                ppu: dir({
                    'hblank_ly_scx_timing-GS': rom(`${TESTDATA}/mooneye/acceptance/ppu/hblank_ly_scx_timing-GS.gb`),
                    'intr_1_2_timing-GS': rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_1_2_timing-GS.gb`),
                    intr_2_0_timing: rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_2_0_timing.gb`),
                    intr_2_mode0_timing: rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_2_mode0_timing.gb`),
                    intr_2_mode0_timing_sprites: rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_2_mode0_timing_sprites.gb`),
                    intr_2_mode3_timing: rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_2_mode3_timing.gb`),
                    intr_2_oam_ok_timing: rom(`${TESTDATA}/mooneye/acceptance/ppu/intr_2_oam_ok_timing.gb`),
                    'lcdon_timing-GS': rom(`${TESTDATA}/mooneye/acceptance/ppu/lcdon_timing-GS.gb`),
                    'lcdon_write_timing-GS': rom(`${TESTDATA}/mooneye/acceptance/ppu/lcdon_write_timing-GS.gb`),
                    stat_irq_blocking: rom(`${TESTDATA}/mooneye/acceptance/ppu/stat_irq_blocking.gb`),
                    stat_lyc_onoff: rom(`${TESTDATA}/mooneye/acceptance/ppu/stat_lyc_onoff.gb`),
                    'vblank_stat_intr-GS': rom(`${TESTDATA}/mooneye/acceptance/ppu/vblank_stat_intr-GS.gb`),
                }),
                serial: dir({
                    'boot_sclk_align-dmgABCmgb': rom(`${TESTDATA}/mooneye/acceptance/serial/boot_sclk_align-dmgABCmgb.gb`),
                }),
                timer: dir({
                    div_write: rom(`${TESTDATA}/mooneye/acceptance/timer/div_write.gb`),
                    rapid_toggle: rom(`${TESTDATA}/mooneye/acceptance/timer/rapid_toggle.gb`),
                    tim00: rom(`${TESTDATA}/mooneye/acceptance/timer/tim00.gb`),
                    tim00_div_trigger: rom(`${TESTDATA}/mooneye/acceptance/timer/tim00_div_trigger.gb`),
                    tim01: rom(`${TESTDATA}/mooneye/acceptance/timer/tim01.gb`),
                    tim01_div_trigger: rom(`${TESTDATA}/mooneye/acceptance/timer/tim01_div_trigger.gb`),
                    tim10: rom(`${TESTDATA}/mooneye/acceptance/timer/tim10.gb`),
                    tim10_div_trigger: rom(`${TESTDATA}/mooneye/acceptance/timer/tim10_div_trigger.gb`),
                    tim11: rom(`${TESTDATA}/mooneye/acceptance/timer/tim11.gb`),
                    tim11_div_trigger: rom(`${TESTDATA}/mooneye/acceptance/timer/tim11_div_trigger.gb`),
                    tima_reload: rom(`${TESTDATA}/mooneye/acceptance/timer/tima_reload.gb`),
                    tima_write_reloading: rom(`${TESTDATA}/mooneye/acceptance/timer/tima_write_reloading.gb`),
                    tma_write_reloading: rom(`${TESTDATA}/mooneye/acceptance/timer/tma_write_reloading.gb`),
                }),
                add_sp_e_timing: rom(`${TESTDATA}/mooneye/acceptance/add_sp_e_timing.gb`),
                'boot_div-dmgABCmgb': rom(`${TESTDATA}/mooneye/acceptance/boot_div-dmgABCmgb.gb`),
                'boot_hwio-dmgABCmgb': rom(`${TESTDATA}/mooneye/acceptance/boot_hwio-dmgABCmgb.gb`),
                'boot_regs-dmgABC': rom(`${TESTDATA}/mooneye/acceptance/boot_regs-dmgABC.gb`),
                call_cc_timing: rom(`${TESTDATA}/mooneye/acceptance/call_cc_timing.gb`),
                call_cc_timing2: rom(`${TESTDATA}/mooneye/acceptance/call_cc_timing2.gb`),
                call_timing: rom(`${TESTDATA}/mooneye/acceptance/call_timing.gb`),
                call_timing2: rom(`${TESTDATA}/mooneye/acceptance/call_timing2.gb`),
                'di_timing-GS': rom(`${TESTDATA}/mooneye/acceptance/di_timing-GS.gb`),
                div_timing: rom(`${TESTDATA}/mooneye/acceptance/div_timing.gb`),
                ei_sequence: rom(`${TESTDATA}/mooneye/acceptance/ei_sequence.gb`),
                ei_timing: rom(`${TESTDATA}/mooneye/acceptance/ei_timing.gb`),
                halt_ime0_ei: rom(`${TESTDATA}/mooneye/acceptance/halt_ime0_ei.gb`),
                halt_ime0_nointr_timing: rom(`${TESTDATA}/mooneye/acceptance/halt_ime0_nointr_timing.gb`),
                halt_ime1_timing: rom(`${TESTDATA}/mooneye/acceptance/halt_ime1_timing.gb`),
                'halt_ime1_timing2-GS': rom(`${TESTDATA}/mooneye/acceptance/halt_ime1_timing2-GS.gb`),
                if_ie_registers: rom(`${TESTDATA}/mooneye/acceptance/if_ie_registers.gb`),
                intr_timing: rom(`${TESTDATA}/mooneye/acceptance/intr_timing.gb`),
                jp_cc_timing: rom(`${TESTDATA}/mooneye/acceptance/jp_cc_timing.gb`),
                jp_timing: rom(`${TESTDATA}/mooneye/acceptance/jp_timing.gb`),
                ld_hl_sp_e_timing: rom(`${TESTDATA}/mooneye/acceptance/ld_hl_sp_e_timing.gb`),
                oam_dma_restart: rom(`${TESTDATA}/mooneye/acceptance/oam_dma_restart.gb`),
                oam_dma_start: rom(`${TESTDATA}/mooneye/acceptance/oam_dma_start.gb`),
                oam_dma_timing: rom(`${TESTDATA}/mooneye/acceptance/oam_dma_timing.gb`),
                pop_timing: rom(`${TESTDATA}/mooneye/acceptance/pop_timing.gb`),
                push_timing: rom(`${TESTDATA}/mooneye/acceptance/push_timing.gb`),
                rapid_di_ei: rom(`${TESTDATA}/mooneye/acceptance/rapid_di_ei.gb`),
                ret_cc_timing: rom(`${TESTDATA}/mooneye/acceptance/ret_cc_timing.gb`),
                ret_timing: rom(`${TESTDATA}/mooneye/acceptance/ret_timing.gb`),
                reti_intr_timing: rom(`${TESTDATA}/mooneye/acceptance/reti_intr_timing.gb`),
                reti_timing: rom(`${TESTDATA}/mooneye/acceptance/reti_timing.gb`),
                rst_timing: rom(`${TESTDATA}/mooneye/acceptance/rst_timing.gb`),
            }),
            'emulator-only': dir({
                mbc1: dir({
                    bits_bank1: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/bits_bank1.gb`),
                    bits_bank2: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/bits_bank2.gb`),
                    bits_mode: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/bits_mode.gb`),
                    bits_ramg: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/bits_ramg.gb`),
                    multicart_rom_8Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/multicart_rom_8Mb.gb`),
                    ram_256kb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/ram_256kb.gb`),
                    ram_64kb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/ram_64kb.gb`),
                    rom_16Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_16Mb.gb`),
                    rom_1Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_1Mb.gb`),
                    rom_2Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_2Mb.gb`),
                    rom_4Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_4Mb.gb`),
                    rom_512kb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_512kb.gb`),
                    rom_8Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc1/rom_8Mb.gb`),
                }),
                mbc2: dir({
                    bits_ramg: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/bits_ramg.gb`),
                    bits_romb: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/bits_romb.gb`),
                    bits_unused: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/bits_unused.gb`),
                    ram: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/ram.gb`),
                    rom_1Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/rom_1Mb.gb`),
                    rom_2Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/rom_2Mb.gb`),
                    rom_512kb: rom(`${TESTDATA}/mooneye/emulator-only/mbc2/rom_512kb.gb`),
                }),
                mbc5: dir({
                    rom_16Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_16Mb.gb`),
                    rom_1Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_1Mb.gb`),
                    rom_2Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_2Mb.gb`),
                    rom_32Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_32Mb.gb`),
                    rom_4Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_4Mb.gb`),
                    rom_512kb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_512kb.gb`),
                    rom_64Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_64Mb.gb`),
                    rom_8Mb: rom(`${TESTDATA}/mooneye/emulator-only/mbc5/rom_8Mb.gb`),
                }),
            }),
        }),

        'dmg-acid2': rom(`${TESTDATA}/dmg-acid2/dmg-acid2.gb`),
        dmg_mode1_stat_int: rom(`${TESTDATA}/dmg_mode1_stat_int/dmg_mode1_stat_int_tests.gb`),
    }),
});

// svg icons from bootstrap icons - only using a few so probably worth
// just defining each SVG manually instead of adding a CDN dependency

export const CHEVRON_ICON_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M4.146 3.646a.5.5 0 0 0 0 .708L7.793 8l-3.647 3.646a.5.5 0 0 0 .708.708l4-4a.5.5
0 0 0 0-.708l-4-4a.5.5 0 0 0-.708 0M11.5 1a.5.5 0 0 1 .5.5v13a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5"/></svg>
`
export const UNLOCKED_ICON_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M8 0c1.07 0 2.041.42 2.759 1.104l.14.14.062.08a.5.5 0 0
1-.71.675l-.076-.066-.216-.205A3 3 0 0 0 5 4v2h6.5A2.5 2.5 0 0 1 14 8.5v5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5
2.5 0 0 1 2 13.5v-5a2.5 2.5 0 0 1 2-2.45V4a4 4 0 0 1 4-4M4.5 7A1.5 1.5 0 0 0 3 8.5v5A1.5 1.5 0 0 0 4.5
15h7a1.5 1.5 0 0 0 1.5-1.5v-5A1.5 1.5 0 0 0 11.5 7z"/></svg>
`
export const LOCKED_ICON_SVG = `
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M8 0a4 4 0 0 1 4 4v2.05a2.5 2.5 0 0 1 2 2.45v5a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5
0 0 1 2 13.5v-5a2.5 2.5 0 0 1 2-2.45V4a4 4 0 0 1 4-4M4.5 7A1.5 1.5 0 0 0 3 8.5v5A1.5 1.5 0 0 0 4.5 15h7a1.5
1.5 0 0 0 1.5-1.5v-5A1.5 1.5 0 0 0 11.5 7zM8 1a3 3 0 0 0-3 3v2h6V4a3 3 0 0 0-3-3"/></svg>
`
