[keybinds]
start = return
select = space
b = s
a = a
down = k
up = i
left = j
right = l

[rom]
romlib = romlib
bootrom = romlib/bootroms/dmg_boot.bin
use_bootrom = false

[bbram]
path = bbram
# valid values: hash, name, none
config = hash
